namespace: ecs-system
vSphereCluster:
  name: cluster-ecs

datacenter:
  name: dc-ecs

vc:
  isoImagePath: "[datastore1] VMware-VCSA-all-8.0.2-23319993.iso"
  vmSize: "small"
  vmName: "SiteManagement"

hosts:

ntpServers:

# Arrays are put as maps. name: <object>. This way, we can use in built helm values merging logic.
storages:
  vsandatastore:
    # Optionally you can disable, if you don't need vsan.
    required: true
    type: vsan
    vsan:

networkTemplates:
  management:
    uplinks:
    teamingPolicy:

switches:
  dvs-ecs:
    networks:
      management:
        netTemplate: management
      vmotion:
        netTemplate: management
      vsan:
        netTemplate: management
      iscsi:
        netTemplate: management
      workload:
        netTemplate: management
    niocSpecs:
    uplinks:
    mtu: 9000

computeResources:
  management:
  workload:
  k8s:

vmFolders:
  management:
  workload:
  k8s:

licenses:
  name: sddc-licenses
  content:
    esxi:
    vcenter:
    vsan:
