{{- range $name, $spec := .Values.storages }}
{{- if $spec.required }}
---
apiVersion: ecs.broadcom.com/v1alpha1
kind: SDDCVSphereDatastore
metadata:
  labels:
    ecs.broadcom.com/sddc: {{ $.Values.name }}
    ecs.broadcom.com/edge-cluster: {{ $.Values.vSphereCluster.name }}
  name: "{{ $name }}"
  namespace: "{{ $.Values.namespace }}"
spec:
  type: {{ $spec.type }}
  {{- if $spec.vsan }}
  vsan: {{- $spec.vsan | toYaml | nindent 4 }}
  {{- end }}
  {{- if $spec.iscsi }}
  iscsi: {{- $spec.iscsi | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

---

