{{- range $name, $switchSpec := .Values.switches }}
---
apiVersion: ecs.broadcom.com/v1alpha1
kind: SDDCVSphereDVSwitch
metadata:
  labels:
    ecs.broadcom.com/sddc: {{ $.Values.name }}
    ecs.broadcom.com/edge-cluster: {{ $.Values.vSphereCluster.name }}
  name: {{ $name }}
  namespace: "{{ $.Values.namespace }}"
spec:
  niocSpecs: {{- $switchSpec.niocSpecs | toYaml | indent 2 }}
  uplinks: {{ $switchSpec.uplinks | toYaml | nindent 2 }}
  mtu: {{ $switchSpec.mtu | default 9000 }}

{{- range $key, $val := $switchSpec }}
{{- if eq $key "networks" }}
  dvpgs:
{{- range $netName, $networkSpec := $switchSpec.networks }}
  - name: {{ $netName }}
{{- if and (kindIs "map" $networkSpec) (hasKey $networkSpec "netTemplate") }}
    {{- $ref := get $networkSpec "netTemplate" }}
    {{- if and (kindIs "map" $.Values.networkTemplates) (hasKey $.Values.networkTemplates $ref) }}
    {{- $refSpec := get $.Values.networkTemplates $ref }}
    vlanId: {{ $refSpec.vlanId }}
    mtu: {{ $refSpec.mtu | default 1500 }}
    {{- if $refSpec.activeUplinks }}
    {{- $uplRef := $refSpec.activeUplinks }}
    {{- if and (kindIs "map" $.Values.uplinkGroups) (hasKey $.Values.uplinkGroups $uplRef) }}
    {{- $uplRefSpec := get $.Values.uplinkGroups $uplRef }}
    activeUplinks: {{ $uplRefSpec | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

---

